version: "3"

services:

  redis:
    image: "redis:latest"

  postgres:
    image: "postgres:14.1-alpine"
    
    environment:
      - POSTGRES_PASSWORD=password
  
  
  nginx:
    # nginx must be avaliable
    restart: always
    depends_on:
      - api
      - frontend

    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  
  frontend:
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - "./frontend:/app"
  api:
    depends_on:
      - postgres
      - redis
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - "./server:/app"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=password
      - PGPORT=5432
      

  worker:
    depends_on:
      - redis
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - "/app/node_modules"
      - "./worker:/app"
    
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379