name: deploy-frontend-to-elasticbeanstalk

on:
  push:
    branches: [ "deprecated" ]

jobs:
  deploy-to-aws-elasticbeanstalk:
    runs-on: ubuntu-latest
    env: 
      BUILD_FILE_NAME: deploy_package_ver_${{ github.sha }}.zip
      APPLICATION_NAME: ${{ secrets.AWS_EBS_APPLICATION_NAME }}
      ENVIRONMENT_NAME: ${{ secrets.AWS_EBS_ENVIRONMENT_NAME }} 
      VERSION_LABEL: ver-${{ github.sha }} 
    steps:
      - uses: actions/checkout@v2

      - name: Create a zip package of the folder to deploy
        run: |
              cd  frontend
              zip -r ../$BUILD_FILE_NAME ./

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
        # s3://bucket-name/app_name/
      - name: Put into s3 bucket
        run: aws s3 cp $BUILD_FILE_NAME s3://${{ secrets.AWS_S3_BUCKET_NAME }}/$APPLICATION_NAME/
        
      - name: Create New ElasticBeanstalk Application Version
        env:
            
            S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
            
          
        run: |

              aws elasticbeanstalk create-application-version \
              --application-name $APPLICATION_NAME \
              --source-bundle S3Bucket=$S3_BUCKET,S3Key=$APPLICATION_NAME/$BUILD_FILE_NAME \
              --version-label $VERSION_LABEL \
              --description "commit-sha-${{ github.sha }}" \
              --auto-create-application


      - name: Deploy new ElasticBeanStalk Version
        run: aws elasticbeanstalk update-environment --environment-name $ENVIRONMENT_NAME --version-label $VERSION_LABEL

    